server:
  port: 8763
  context-path: /nessage
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
spring:
  application:
    name: member
  activemq:
    broker-url: tcp://192.168.73.128:61617
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.qq.com
    username: 1775731880@qq.com
    password: gwovxjrsnfracdac
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
    properties:
      mail:
        smtp:
          ssl:
            enable: true
